### ISSUE TITLE
export_evtx.exe -- IndexError: list index out of range

### ISSUE THREAD

**Issue by commandline-be** [markmckinnon/Autopsy-Plugins#34] opened 2021-02-15 13:38 UTC
Following my prior post on process_evtx and other failing i tested export_evtx.exe from a cmd prompt

Any kind of starting this executable resulted in

export_evtx.exe 
Traceback (most recent call last):
  File "<string>", line 151, in <module>
IndexError: list index out of range
export_evtx returned -1

**Comment by markmckinnon** [comment] 2021-02-15 13:51
You need to pass the proper parameters to it for it to run.  The parameters can be found in the parse_evtx.py.  For example to run export_evtx you will need to run the following:

export_evtx <path to event log files> <database to save output to>  so it would look something like this

export_evtx c:\autopsy_cases\case_logs\temp\event_logs  c:\autopsy_cases\case_logs\module_output\event_logs\export_evtx.db3

Does that help?

**Comment by commandline-be** [comment] 2021-02-15 13:54
seeing the executable is over 5 years old, and it meets what i expected, must be so

i keep on being stuck with process_evtx and the python script not doing anything so i'm simply trying anything, the logs show nothing relevant to python not working or process_evtx failing

**Comment by shannaniggans** [comment] 2022-04-03 00:30
@commandline-be ill close this as a duplicate of #33 -> I am looking at the Parse_Evtx module the error and also why it hangs in that open issue.

**Closed by shannaniggans** 2022-04-03 00:30 UTC
